#!/usr/bin/env sh
set -e
# Cleanup files passed as arguments separated by null characters (so it can
# handle files containing newlines).
#
# Please follow the following 2 rules, unless called from a rebase command
# suggested by cleanrebase (i.e. via cleanupcommit). The cleanrebase tool
# depends on it:
# 1. always run on all files in the index, i.e. use:
#    ./cleanupindex
# 2. always commit with the following exact commit message:
#    git commit -a -m 'run cleanup script'

# Strip trailing whitespace.
grep -Z -d skip -l . "$@" |
  xargs -0 -r sed -i 's/ *$//g'

# See #7995 comment #4.
# It is faster to grep for the pattern before calling sed.
# That is also why this is not a pure sed script.
grep -Z -d skip -l . "$@" |
  xargs -0 -r grep -Z -l 'ptext (sLit "[^"]*")' |
  xargs -0 -r sed -i 's/ptext (sLit \("[^"]*"\))/text \1/'
